// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { SearchAgentInstanceHistoryData, SearchAgentInstanceHistoryErrors, SearchAgentInstanceHistoryResponses, SearchAgentInstancesData, SearchAgentInstancesErrors, SearchAgentInstancesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Search agent instances
 *
 * Search for agent instances based on given criteria.
 */
export const searchAgentInstances = <ThrowOnError extends boolean = false>(options?: Options<SearchAgentInstancesData, ThrowOnError>): RequestResult<SearchAgentInstancesResponses, SearchAgentInstancesErrors, ThrowOnError> => (options?.client ?? client).post<SearchAgentInstancesResponses, SearchAgentInstancesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'basic', type: 'http' }],
    url: '/agent-instances/search',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Search agent instance history
 *
 * Searches the conversation history of an agent instance. Committed items
 * are returned by default.
 *
 */
export const searchAgentInstanceHistory = <ThrowOnError extends boolean = false>(options: Options<SearchAgentInstanceHistoryData, ThrowOnError>): RequestResult<SearchAgentInstanceHistoryResponses, SearchAgentInstanceHistoryErrors, ThrowOnError> => (options.client ?? client).post<SearchAgentInstanceHistoryResponses, SearchAgentInstanceHistoryErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'basic', type: 'http' }],
    url: '/agent-instances/{agentInstanceKey}/history/search',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
