// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: '{schema}://{host}:{port}/v2' | (string & {});
};

/**
 * Advanced filter
 *
 * Advanced AgentInstanceHistoryCommitStatusEnum filter.
 */
export type AdvancedAgentInstanceHistoryCommitStatusFilter = {
    /**
     * Checks for equality with the provided value.
     */
    $eq?: AgentInstanceHistoryCommitStatusEnum;
    /**
     * Checks for inequality with the provided value.
     */
    $neq?: AgentInstanceHistoryCommitStatusEnum;
    /**
     * Checks if the current property exists.
     */
    $exists?: boolean;
    /**
     * Checks if the property matches any of the provided values.
     */
    $in?: Array<AgentInstanceHistoryCommitStatusEnum>;
};

/**
 * Advanced filter
 *
 * Advanced AgentInstanceHistoryRoleEnum filter.
 */
export type AdvancedAgentInstanceHistoryRoleFilter = {
    /**
     * Checks for equality with the provided value.
     */
    $eq?: AgentInstanceHistoryRoleEnum;
    /**
     * Checks for inequality with the provided value.
     */
    $neq?: AgentInstanceHistoryRoleEnum;
    /**
     * Checks if the current property exists.
     */
    $exists?: boolean;
    /**
     * Checks if the property matches any of the provided values.
     */
    $in?: Array<AgentInstanceHistoryRoleEnum>;
};

/**
 * Advanced filter
 *
 * Advanced AgentInstanceStatusEnum filter.
 */
export type AdvancedAgentInstanceStatusFilter = {
    /**
     * Checks for equality with the provided value.
     */
    $eq?: AgentInstanceStatusEnum;
    /**
     * Checks for inequality with the provided value.
     */
    $neq?: AgentInstanceStatusEnum;
    /**
     * Checks if the current property exists.
     */
    $exists?: boolean;
    /**
     * Checks if the property matches any of the provided values.
     */
    $in?: Array<AgentInstanceStatusEnum>;
    $like?: LikeFilter;
};

/**
 * The definition of an agent instance. Set at creation, but can change later via a
 * CONFIGURATION history item.
 *
 */
export type AgentInstanceDefinitionResult = {
    /**
     * The LLM model identifier (for example, gpt-4o).
     */
    model: string;
    /**
     * The LLM provider (for example, openai or anthropic).
     */
    provider: string;
    /**
     * The system prompt configured for this agent instance, as content blocks.
     */
    systemPrompt: Array<AgentInstanceMessageContent>;
};

/**
 * Document content
 *
 * A Camunda Document Store reference content block.
 */
export type AgentInstanceDocumentContent = {
    /**
     * The content type discriminator.
     */
    contentType: string;
    /**
     * A reference to a document stored in the Camunda Document Store.
     */
    documentReference: DocumentReference;
};

/**
 * Agent instance search filter.
 */
export type AgentInstanceFilter = {
    /**
     * The unique key of the agent instance.
     */
    agentInstanceKey?: AgentInstanceKeyFilterProperty;
    /**
     * The key of the agent definition this agent instance is an instance of.
     */
    agentDefinitionKey?: AgentDefinitionKeyFilterProperty;
    /**
     * The current status of the agent instance.
     */
    status?: AgentInstanceStatusFilterProperty;
    /**
     * The BPMN element ID of the agent task.
     */
    elementId?: ElementIdFilterProperty;
    /**
     * The key of the process instance that owns this agent instance.
     */
    processInstanceKey?: ProcessInstanceKeyFilterProperty;
    /**
     * The key of the root process instance. Filters agent instances belonging to a specific
     * call hierarchy. The root process instance is the top-level ancestor in the process
     * instance hierarchy.
     *
     */
    rootProcessInstanceKey?: ProcessInstanceKeyFilterProperty;
    /**
     * The key of the process definition associated with this agent instance.
     */
    processDefinitionKey?: ProcessDefinitionKeyFilterProperty;
    /**
     * The tenant ID of the agent instance.
     */
    tenantId?: StringFilterProperty;
    /**
     * The creation date of the agent instance.
     */
    creationDate?: DateTimeFilterProperty;
    /**
     * The date the agent instance was last updated.
     */
    lastUpdatedDate?: DateTimeFilterProperty;
    /**
     * The completion date of the agent instance.
     */
    completionDate?: DateTimeFilterProperty;
    /**
     * The keys of element instances associated with this agent instance.
     * If multiple keys are provided, the filter matches agent instances associated with all of the provided keys at the same time.
     */
    elementInstanceKeys?: Array<ElementInstanceKeyFilterProperty>;
    /**
     * The BPMN process ID of the process definition associated with this agent instance.
     */
    processDefinitionId?: StringFilterProperty;
    /**
     * The version of the process definition associated with this agent instance.
     */
    processDefinitionVersion?: IntegerFilterProperty;
    /**
     * The version tag of the process definition associated with this agent instance.
     */
    processDefinitionVersionTag?: StringFilterProperty;
};

/**
 * The commit status of a history item.
 * COMMITTED: the producing job completed successfully.
 * PENDING: the producing job is still active (in-flight).
 * DISCARDED: the producing job failed; this item was superseded by a later activation.
 *
 */
export type AgentInstanceHistoryCommitStatusEnum = 'COMMITTED' | 'PENDING' | 'DISCARDED';

/**
 * AgentInstanceHistoryCommitStatusEnum property with full advanced search capabilities.
 */
export type AgentInstanceHistoryCommitStatusFilterProperty = AgentInstanceHistoryCommitStatusEnum | AdvancedAgentInstanceHistoryCommitStatusFilter;

/**
 * Agent instance history item search filter.
 */
export type AgentInstanceHistoryFilter = {
    /**
     * The unique key of the history item.
     */
    historyItemKey?: AgentHistoryItemKeyFilterProperty;
    /**
     * The role of the history item.
     */
    role?: AgentInstanceHistoryRoleFilterProperty;
    /**
     * The key of the element instance under which the history item was produced.
     */
    elementInstanceKey?: ElementInstanceKeyFilterProperty;
    /**
     * The key of the job activation that produced the history item.
     */
    jobKey?: JobKeyFilterProperty;
    /**
     * Filter by loop iteration number.
     */
    loopIteration?: IntegerFilterProperty;
    /**
     * The commit status of the history item. Defaults to COMMITTED only.
     * Include PENDING or DISCARDED explicitly to debug in-flight or failed activations.
     *
     */
    commitStatus?: AgentInstanceHistoryCommitStatusFilterProperty;
    /**
     * The timestamp when the history item was produced.
     */
    producedAt?: DateTimeFilterProperty;
};

/**
 * Per-call token and latency metrics for an ASSISTANT history item.
 */
export type AgentInstanceHistoryItemMetrics = {
    /**
     * Input tokens consumed by this LLM call. Null when not provided.
     */
    inputTokens: number | null;
    /**
     * Output tokens produced by this LLM call. Null when not provided.
     */
    outputTokens: number | null;
    /**
     * Reasoning tokens consumed by this LLM call. Null when not provided.
     */
    reasoningTokenCount: number | null;
    /**
     * Cache-creation tokens consumed by this LLM call. Null when not provided.
     */
    cacheCreationTokenCount: number | null;
    /**
     * Cache-read tokens consumed by this LLM call. Null when not provided.
     */
    cacheReadTokenCount: number | null;
    /**
     * Wall-clock duration of the LLM call in milliseconds. Null when not provided.
     */
    durationMs: number | null;
};

/**
 * A single conversation history item belonging to an agent instance.
 */
export type AgentInstanceHistoryItemResult = {
    /**
     * The unique key for this history item. Stable and sortable by creation order.
     */
    historyItemKey: AgentHistoryItemKey;
    /**
     * The client-supplied identifier this item was created with. Empty for items that don't
     * carry one. Not unique: a job can be re-activated under a superseded lease any number
     * of times before it completes, so one historyItemId can have zero or more DISCARDED
     * records and at most one COMMITTED record, since only historyItemKey is guaranteed
     * unique. Filter by commitStatus rather than assuming one record per historyItemId.
     *
     */
    historyItemId: HistoryItemId;
    /**
     * The key of the agent instance this item belongs to.
     */
    agentInstanceKey: AgentInstanceKey;
    /**
     * The key of the AI Agent Task or ad-hoc sub-process element instance under which this item was produced.
     */
    elementInstanceKey: ElementInstanceKey;
    /**
     * The key of the job activation during which this item was produced.
     */
    jobKey: JobKey;
    /**
     * The lease token of the activation that produced this item.
     */
    jobLeaseToken: JobLeaseToken;
    /**
     * The loop iteration this item belongs to.
     */
    loopIteration: LoopIterationId;
    /**
     * The role of this history item in the conversation.
     */
    role: AgentInstanceHistoryRoleEnum;
    /**
     * The content blocks of this history item.
     */
    content: Array<AgentInstanceMessageContent>;
    /**
     * Tool calls for this item. Empty for USER items and ASSISTANT items with no tool dispatches.
     * ASSISTANT items: dispatched tool calls.
     * TOOL_RESULT items: single-entry array referencing the originating tool call.
     *
     */
    toolCalls: Array<AgentInstanceToolCall>;
    /**
     * Per-call token and latency metrics. Null when metrics were not provided at creation time.
     */
    metrics: AgentInstanceHistoryItemMetrics | null;
    /**
     * The commit status of this history item.
     */
    commitStatus: AgentInstanceHistoryCommitStatusEnum;
    /**
     * The agent-side timestamp of when this message was produced.
     */
    producedAt: string;
    /**
     * The complete list of tools available to the agent as of this entry. CONFIGURATION
     * items only; empty for other roles.
     *
     */
    tools: Array<AgentTool>;
    /**
     * The LLM model identifier as of this entry. CONFIGURATION items only; null for other
     * roles.
     *
     */
    model: string | null;
    /**
     * The LLM provider as of this entry. CONFIGURATION items only; null for other roles.
     *
     */
    provider: string | null;
    /**
     * The operational limits as of this entry. CONFIGURATION items only; -1 on any field
     * means "no limit configured" for other roles.
     *
     */
    limits: AgentInstanceLimits;
    /**
     * The system prompt, as content blocks, as of this entry. CONFIGURATION items only;
     * empty for other roles.
     *
     */
    systemPrompt: Array<AgentInstanceMessageContent>;
};

/**
 * The role of a history item in the agent conversation.
 */
export type AgentInstanceHistoryRoleEnum = 'USER' | 'ASSISTANT' | 'TOOL_RESULT' | 'CONFIGURATION';

/**
 * AgentInstanceHistoryRoleEnum property with full advanced search capabilities.
 */
export type AgentInstanceHistoryRoleFilterProperty = AgentInstanceHistoryRoleEnum | AdvancedAgentInstanceHistoryRoleFilter;

/**
 * Agent instance history search request.
 */
export type AgentInstanceHistorySearchQuery = SearchQueryRequest & {
    /**
     * Sort field criteria.
     */
    sort?: Array<AgentInstanceHistorySearchQuerySortRequest>;
    /**
     * The history item search filters.
     */
    filter?: AgentInstanceHistoryFilter;
};

/**
 * Agent instance history search response.
 */
export type AgentInstanceHistorySearchQueryResult = SearchQueryResponse & {
    /**
     * The matching history items.
     */
    items: Array<AgentInstanceHistoryItemResult>;
};

export type AgentInstanceHistorySearchQuerySortRequest = {
    /**
     * The field to sort by.
     */
    field: 'producedAt' | 'historyItemKey' | 'loopIteration';
    order?: SortOrderEnum;
};

/**
 * The configured limits for an agent instance, set once at creation.
 */
export type AgentInstanceLimits = {
    /**
     * Maximum LLM calls allowed. -1 if no limit is configured.
     */
    maxModelCalls: number;
    /**
     * Maximum tool calls allowed. -1 if no limit is configured.
     */
    maxToolCalls: number;
    /**
     * Maximum total tokens allowed. -1 if no limit is configured.
     */
    maxTokens: number;
};

/**
 * A single content block within a history item. Discriminated by `contentType`.
 */
export type AgentInstanceMessageContent = ({
    contentType: 'TEXT';
} & AgentInstanceTextContent) | ({
    contentType: 'DOCUMENT';
} & AgentInstanceDocumentContent) | ({
    contentType: 'OBJECT';
} & AgentInstanceObjectContent);

/**
 * Aggregated metrics for an agent instance across all model calls.
 */
export type AgentInstanceMetrics = {
    /**
     * Total input tokens consumed across all model calls.
     */
    inputTokens: number;
    /**
     * Total output tokens produced across all model calls.
     */
    outputTokens: number;
    /**
     * Total reasoning tokens consumed across all model calls.
     */
    reasoningTokenCount: number;
    /**
     * Total tokens used to create prompt cache entries across all model calls.
     */
    cacheCreationTokenCount: number;
    /**
     * Total tokens read from prompt cache across all model calls.
     */
    cacheReadTokenCount: number;
    /**
     * Total number of LLM calls made.
     */
    modelCalls: number;
    /**
     * Total number of tool calls made.
     */
    toolCalls: number;
};

/**
 * Object content
 *
 * An arbitrary structured content block. Accepts any valid JSON value:
 * objects, arrays, numbers, booleans, or strings.
 * Use TEXT content for human-readable natural language;
 * use OBJECT content for machine-readable structured data.
 *
 */
export type AgentInstanceObjectContent = {
    /**
     * The content type discriminator.
     */
    contentType: string;
    /**
     * Arbitrary structured content — any valid JSON value (object, array, number, boolean, or string).
     */
    object: unknown;
};

export type AgentInstanceResult = {
    /**
     * The unique key for this agent instance.
     */
    agentInstanceKey: AgentInstanceKey;
    /**
     * The key of the agent definition this agent instance is an instance of.
     */
    agentDefinitionKey: AgentDefinitionKey;
    status: AgentInstanceStatusEnum;
    /**
     * The definition of the agent, including model, provider, and system prompt. Set at
     * creation, but can change later via a CONFIGURATION history item.
     *
     */
    definition: AgentInstanceDefinitionResult;
    /**
     * Aggregated metrics across all loopIterations of this agent instance. Includes
     * history items later discarded: metrics are counted when an item is accepted,
     * not when it's committed.
     *
     */
    metrics: AgentInstanceMetrics;
    /**
     * The configured limits for this agent instance, set once at creation.
     */
    limits: AgentInstanceLimits;
    /**
     * The tools available to the agent.
     */
    tools: Array<AgentTool>;
    /**
     * The BPMN element ID of the ad-hoc sub-process or AI agent task that owns this agent instance.
     */
    elementId: ElementId;
    /**
     * The key of the process instance that owns this agent instance.
     */
    processInstanceKey: ProcessInstanceKey;
    /**
     * The key of the root process instance. The root process instance is the top-level
     * ancestor in the process instance hierarchy.
     *
     */
    rootProcessInstanceKey: ProcessInstanceKey;
    /**
     * The key of the process definition associated with this agent instance.
     */
    processDefinitionKey: ProcessDefinitionKey;
    /**
     * The BPMN process ID of the process definition associated with this agent instance.
     */
    processDefinitionId: ProcessDefinitionId;
    /**
     * The version of the process definition associated with this agent instance.
     */
    processDefinitionVersion: number;
    /**
     * The version tag of the process definition associated with this agent instance.
     */
    processDefinitionVersionTag: string | null;
    /**
     * The tenant ID of this agent instance.
     */
    tenantId: TenantId;
    /**
     * The date when this agent instance was created.
     */
    creationDate: string;
    /**
     * The date when this agent instance was last updated.
     */
    lastUpdatedDate: string;
    /**
     * The date when this agent instance completed. Null while the agent is still running.
     */
    completionDate: string | null;
    /**
     * The keys of all element instances associated with this agent instance.
     */
    elementInstanceKeys: Array<ElementInstanceKey>;
};

/**
 * Agent instance search request.
 */
export type AgentInstanceSearchQuery = SearchQueryRequest & {
    /**
     * Sort field criteria.
     */
    sort?: Array<AgentInstanceSearchQuerySortRequest>;
    /**
     * The agent instance search filters.
     */
    filter?: AgentInstanceFilter;
};

/**
 * Agent instance search response.
 */
export type AgentInstanceSearchQueryResult = SearchQueryResponse & {
    /**
     * The matching agent instances.
     */
    items: Array<AgentInstanceResult>;
};

export type AgentInstanceSearchQuerySortRequest = {
    /**
     * The field to sort by.
     */
    field: 'agentInstanceKey' | 'agentDefinitionKey' | 'status' | 'elementId' | 'processInstanceKey' | 'rootProcessInstanceKey' | 'processDefinitionKey' | 'tenantId' | 'creationDate' | 'lastUpdatedDate' | 'completionDate';
    order?: SortOrderEnum;
};

/**
 * The current status of an agent instance.
 */
export type AgentInstanceStatusEnum = 'UNKNOWN' | 'COMPLETED' | 'IDLE' | 'INITIALIZING' | 'THINKING' | 'TOOL_CALLING' | 'TOOL_DISCOVERY';

/**
 * AgentInstanceStatusEnum property with full advanced search capabilities.
 */
export type AgentInstanceStatusFilterProperty = AgentInstanceStatusEnum | AdvancedAgentInstanceStatusFilter;

/**
 * Text content
 *
 * A plain-text content block.
 */
export type AgentInstanceTextContent = {
    /**
     * The content type discriminator.
     */
    contentType: string;
    /**
     * The text content.
     */
    text: string;
};

/**
 * A tool call associated with a history item. Used in both ASSISTANT and TOOL_RESULT items.
 *
 */
export type AgentInstanceToolCall = {
    /**
     * The LLM-assigned tool call ID. Correlates ASSISTANT items to their matching TOOL_RESULT items.
     */
    toolCallId: string;
    /**
     * The LLM-visible tool name.
     */
    toolName: string;
    /**
     * The BPMN element ID handling this tool.
     */
    elementId: ElementId | null;
    /**
     * The tool call arguments as provided by the LLM. May be null or populated on
     * any item, including TOOL_RESULT.
     *
     */
    arguments: {
        [key: string]: unknown;
    } | null;
};

/**
 * A tool available to the agent.
 */
export type AgentTool = {
    /**
     * The tool name as visible to the LLM.
     */
    name: string;
    /**
     * A human-readable description of the tool.
     */
    description: string | null;
    /**
     * The BPMN element ID of the tool element within the ad-hoc sub-process.
     */
    elementId: ElementId | null;
};

export type _1AgentInstances1Search = unknown;

export type _1AgentInstances1AgentInstanceKey1History1Search = unknown;

/**
 * The end cursor in a search query result set.
 */
export type EndCursor = string;

/**
 * The start cursor in a search query result set.
 */
export type StartCursor = string;

/**
 * Document Id that uniquely identifies a document.
 */
export type DocumentId = string;

/**
 * Information about the document that is returned in responses.
 */
export type DocumentMetadataResponse = {
    /**
     * The content type of the document.
     */
    contentType: string;
    /**
     * The name of the file.
     */
    fileName: string;
    /**
     * The date and time when the document expires.
     */
    expiresAt: string | null;
    /**
     * The size of the document in bytes.
     */
    size: number;
    /**
     * The ID of the process definition that created the document.
     */
    processDefinitionId: ProcessDefinitionId | null;
    /**
     * The key of the process instance that created the document.
     */
    processInstanceKey: ProcessInstanceKey | null;
    /**
     * Custom properties of the document.
     */
    customProperties: {
        [key: string]: unknown;
    };
};

export type DocumentReference = {
    /**
     * Document discriminator. Always set to "camunda".
     */
    'camunda.document.type': 'camunda';
    /**
     * The ID of the document store.
     */
    storeId: string;
    /**
     * The ID of the document.
     */
    documentId: DocumentId;
    /**
     * The hash of the document.
     */
    contentHash: string | null;
    metadata: DocumentMetadataResponse;
};

/**
 * Advanced filter
 *
 * Advanced date-time filter.
 */
export type AdvancedDateTimeFilter = {
    /**
     * Checks for equality with the provided value.
     */
    $eq?: string;
    /**
     * Checks for inequality with the provided value.
     */
    $neq?: string;
    /**
     * Checks if the current property exists.
     */
    $exists?: boolean;
    /**
     * Greater than comparison with the provided value.
     */
    $gt?: string;
    /**
     * Greater than or equal comparison with the provided value.
     */
    $gte?: string;
    /**
     * Lower than comparison with the provided value.
     */
    $lt?: string;
    /**
     * Lower than or equal comparison with the provided value.
     */
    $lte?: string;
    /**
     * Checks if the property matches any of the provided values.
     */
    $in?: Array<string>;
};

/**
 * Advanced filter
 *
 * Advanced integer (int32) filter.
 */
export type AdvancedIntegerFilter = {
    /**
     * Checks for equality with the provided value.
     */
    $eq?: number;
    /**
     * Checks for inequality with the provided value.
     */
    $neq?: number;
    /**
     * Checks if the current property exists.
     */
    $exists?: boolean;
    /**
     * Greater than comparison with the provided value.
     */
    $gt?: number;
    /**
     * Greater than or equal comparison with the provided value.
     */
    $gte?: number;
    /**
     * Lower than comparison with the provided value.
     */
    $lt?: number;
    /**
     * Lower than or equal comparison with the provided value.
     */
    $lte?: number;
    /**
     * Checks if the property matches any of the provided values.
     */
    $in?: Array<number>;
};

/**
 * Advanced filter
 *
 * Advanced string filter.
 */
export type AdvancedStringFilter = BasicStringFilter & {
    $like?: LikeFilter;
};

/**
 * Advanced filter
 *
 * Basic advanced string filter.
 */
export type BasicStringFilter = {
    /**
     * Checks for equality with the provided value.
     */
    $eq?: string;
    /**
     * Checks for inequality with the provided value.
     */
    $neq?: string;
    /**
     * Checks if the current property exists.
     */
    $exists?: boolean;
    /**
     * Checks if the property matches any of the provided values.
     */
    $in?: Array<string>;
    /**
     * Checks if the property matches none of the provided values.
     */
    $notIn?: Array<string>;
};

/**
 * Date-time property with full advanced search capabilities.
 */
export type DateTimeFilterProperty = string | AdvancedDateTimeFilter;

/**
 * Integer property with advanced search capabilities.
 */
export type IntegerFilterProperty = number | AdvancedIntegerFilter;

/**
 * Checks if the property matches the provided like value.
 *
 * Supported wildcard characters are:
 *
 * * `*`: matches zero, one, or multiple characters.
 * * `?`: matches one, single character.
 *
 * Wildcard characters can be escaped with backslash, for instance: `\*`.
 *
 */
export type LikeFilter = string;

/**
 * String property with full advanced search capabilities.
 */
export type StringFilterProperty = string | AdvancedStringFilter;

/**
 * Advanced filter
 *
 * Advanced ElementId filter.
 */
export type AdvancedElementIdFilter = {
    /**
     * Checks for equality with the provided value.
     */
    $eq?: ElementId;
    /**
     * Checks for inequality with the provided value.
     */
    $neq?: ElementId;
    /**
     * Checks if the current property exists.
     */
    $exists?: boolean;
    /**
     * Checks if the property matches any of the provided values.
     */
    $in?: Array<ElementId>;
    /**
     * Checks if the property matches none of the provided values.
     */
    $notIn?: Array<ElementId>;
    $like?: LikeFilter;
};

/**
 * The model-defined id of an element.
 */
export type ElementId = string;

/**
 * ElementId property with full advanced search capabilities.
 */
export type ElementIdFilterProperty = ElementId | AdvancedElementIdFilter;

/**
 * The client-supplied identifier this item was created with.
 */
export type HistoryItemId = string;

/**
 * An opaque, engine-minted fencing token identifying a single activation of a job.
 * Returned by Activate Jobs as `ActivatedJobResult.jobLeaseToken` when the job is
 * activated with a lease, and passed back under the same name on fenced job
 * commands and on agent-instance creation/updates, to prove the caller holds the
 * current lease. The token is opaque: clients may rely on its presence and equality
 * only, and must never construct, parse, or otherwise interpret it beyond equality
 * checks. It cannot be minted client-side; only the engine produces it, exactly once
 * per leased activation, and clients must not depend on any particular internal format.
 *
 */
export type JobLeaseToken = string;

/**
 * A client-provided sequential integer identifying a loop iteration: one pass
 * through an AI agent's loop, during which the model reasons, selects tools,
 * evaluates the result, and decides whether to continue. One iteration covers
 * the input for the LLM call, the call itself, and the tools it dispatches;
 * the results of those tool calls are input to the next iteration. Must be a
 * positive integer, increasing with each loopIteration. Established by the
 * connector when appending the first history item of a loopIteration.
 *
 */
export type LoopIterationId = number;

/**
 * Id of a process definition, from the model. Only ids of process definitions that are deployed are useful.
 */
export type ProcessDefinitionId = string;

/**
 * The unique identifier of the tenant.
 */
export type TenantId = string;

/**
 * Advanced filter
 *
 * Advanced AgentDefinitionKey filter.
 */
export type AdvancedAgentDefinitionKeyFilter = {
    /**
     * Checks for equality with the provided value.
     */
    $eq?: AgentDefinitionKey;
    /**
     * Checks for inequality with the provided value.
     */
    $neq?: AgentDefinitionKey;
    /**
     * Checks if the current property exists.
     */
    $exists?: boolean;
    /**
     * Checks if the property matches any of the provided values.
     */
    $in?: Array<AgentDefinitionKey>;
    /**
     * Checks if the property matches none of the provided values.
     */
    $notIn?: Array<AgentDefinitionKey>;
};

/**
 * Advanced filter
 *
 * Advanced AgentHistoryItemKey filter.
 */
export type AdvancedAgentHistoryItemKeyFilter = {
    /**
     * Checks for equality with the provided value.
     */
    $eq?: AgentHistoryItemKey;
    /**
     * Checks for inequality with the provided value.
     */
    $neq?: AgentHistoryItemKey;
    /**
     * Checks if the current property exists.
     */
    $exists?: boolean;
    /**
     * Checks if the property matches any of the provided values.
     */
    $in?: Array<AgentHistoryItemKey>;
    /**
     * Checks if the property matches none of the provided values.
     */
    $notIn?: Array<AgentHistoryItemKey>;
};

/**
 * Advanced filter
 *
 * Advanced AgentInstanceKey filter.
 */
export type AdvancedAgentInstanceKeyFilter = {
    /**
     * Checks for equality with the provided value.
     */
    $eq?: AgentInstanceKey;
    /**
     * Checks for inequality with the provided value.
     */
    $neq?: AgentInstanceKey;
    /**
     * Checks if the current property exists.
     */
    $exists?: boolean;
    /**
     * Checks if the property matches any of the provided values.
     */
    $in?: Array<AgentInstanceKey>;
    /**
     * Checks if the property matches none of the provided values.
     */
    $notIn?: Array<AgentInstanceKey>;
};

/**
 * Advanced filter
 *
 * Advanced ElementInstanceKey filter.
 */
export type AdvancedElementInstanceKeyFilter = {
    /**
     * Checks for equality with the provided value.
     */
    $eq?: ElementInstanceKey;
    /**
     * Checks for inequality with the provided value.
     */
    $neq?: ElementInstanceKey;
    /**
     * Checks if the current property exists.
     */
    $exists?: boolean;
    /**
     * Checks if the property matches any of the provided values.
     */
    $in?: Array<ElementInstanceKey>;
    /**
     * Checks if the property matches none of the provided values.
     */
    $notIn?: Array<ElementInstanceKey>;
};

/**
 * Advanced filter
 *
 * Advanced JobKey filter.
 */
export type AdvancedJobKeyFilter = {
    /**
     * Checks for equality with the provided value.
     */
    $eq?: JobKey;
    /**
     * Checks for inequality with the provided value.
     */
    $neq?: JobKey;
    /**
     * Checks if the current property exists.
     */
    $exists?: boolean;
    /**
     * Checks if the property matches any of the provided values.
     */
    $in?: Array<JobKey>;
    /**
     * Checks if the property matches none of the provided values.
     */
    $notIn?: Array<JobKey>;
};

/**
 * Advanced filter
 *
 * Advanced ProcessDefinitionKey filter.
 */
export type AdvancedProcessDefinitionKeyFilter = {
    /**
     * Checks for equality with the provided value.
     */
    $eq?: ProcessDefinitionKey;
    /**
     * Checks for inequality with the provided value.
     */
    $neq?: ProcessDefinitionKey;
    /**
     * Checks if the current property exists.
     */
    $exists?: boolean;
    /**
     * Checks if the property matches any of the provided values.
     */
    $in?: Array<ProcessDefinitionKey>;
    /**
     * Checks if the property matches none of the provided values.
     */
    $notIn?: Array<ProcessDefinitionKey>;
};

/**
 * Advanced filter
 *
 * Advanced ProcessInstanceKey filter.
 */
export type AdvancedProcessInstanceKeyFilter = {
    /**
     * Checks for equality with the provided value.
     */
    $eq?: ProcessInstanceKey;
    /**
     * Checks for inequality with the provided value.
     */
    $neq?: ProcessInstanceKey;
    /**
     * Checks if the current property exists.
     */
    $exists?: boolean;
    /**
     * Checks if the property matches any of the provided values.
     */
    $in?: Array<ProcessInstanceKey>;
    /**
     * Checks if the property matches none of the provided values.
     */
    $notIn?: Array<ProcessInstanceKey>;
};

/**
 * System-generated key for an agent definition.
 */
export type AgentDefinitionKey = LongKey;

/**
 * AgentDefinitionKey property with full advanced search capabilities.
 */
export type AgentDefinitionKeyFilterProperty = AgentDefinitionKey | AdvancedAgentDefinitionKeyFilter;

/**
 * System-generated key for an agent history item.
 */
export type AgentHistoryItemKey = LongKey;

/**
 * AgentHistoryItemKey property with full advanced search capabilities.
 */
export type AgentHistoryItemKeyFilterProperty = AgentHistoryItemKey | AdvancedAgentHistoryItemKeyFilter;

/**
 * System-generated key for an agent instance.
 */
export type AgentInstanceKey = LongKey;

/**
 * AgentInstanceKey property with full advanced search capabilities.
 */
export type AgentInstanceKeyFilterProperty = AgentInstanceKey | AdvancedAgentInstanceKeyFilter;

/**
 * System-generated key for a element instance.
 */
export type ElementInstanceKey = LongKey;

/**
 * ElementInstanceKey property with full advanced search capabilities.
 */
export type ElementInstanceKeyFilterProperty = ElementInstanceKey | AdvancedElementInstanceKeyFilter;

/**
 * System-generated key for a job.
 */
export type JobKey = LongKey;

/**
 * JobKey property with full advanced search capabilities.
 */
export type JobKeyFilterProperty = JobKey | AdvancedJobKeyFilter;

/**
 * Zeebe Engine resource key (Java long serialized as string)
 */
export type LongKey = string;

/**
 * System-generated key for a deployed process definition.
 */
export type ProcessDefinitionKey = LongKey;

/**
 * ProcessDefinitionKey property with full advanced search capabilities.
 */
export type ProcessDefinitionKeyFilterProperty = ProcessDefinitionKey | AdvancedProcessDefinitionKeyFilter;

/**
 * System-generated key for a process instance.
 */
export type ProcessInstanceKey = LongKey;

/**
 * ProcessInstanceKey property with full advanced search capabilities.
 */
export type ProcessInstanceKeyFilterProperty = ProcessInstanceKey | AdvancedProcessInstanceKeyFilter;

/**
 * A Problem detail object as described in [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457). There may be additional properties specific to the problem type.
 *
 */
export type ProblemDetail = {
    /**
     * A URI identifying the problem type.
     */
    type: string;
    /**
     * A summary of the problem type.
     */
    title: string;
    /**
     * The HTTP status code for this problem.
     */
    status: number;
    /**
     * An explanation of the problem in more detail.
     */
    detail: string;
    /**
     * A URI path identifying the origin of the problem.
     */
    instance: string;
};

/**
 * Cursor-based backward pagination
 */
export type CursorBackwardPagination = {
    /**
     * Use the `startCursor` value from the previous response to fetch the previous page of results.
     */
    before?: StartCursor;
    /**
     * The maximum number of items to return in one request.
     */
    limit?: number;
};

/**
 * Cursor-based forward pagination
 */
export type CursorForwardPagination = {
    /**
     * Use the `endCursor` value from the previous response to fetch the next page of results.
     */
    after?: EndCursor;
    /**
     * The maximum number of items to return in one request.
     */
    limit?: number;
};

/**
 * Limit-based pagination
 */
export type LimitPagination = {
    /**
     * The maximum number of items to return in one request.
     */
    limit?: number;
};

/**
 * Offset-based pagination
 */
export type OffsetPagination = {
    /**
     * The index of items to start searching from.
     */
    from?: number;
    /**
     * The maximum number of items to return in one request.
     */
    limit?: number;
};

/**
 * Pagination criteria. Can use offset-based pagination (from/limit) OR cursor-based pagination (after/before + limit), but not both.
 */
export type SearchQueryPageRequest = LimitPagination | OffsetPagination | CursorForwardPagination | CursorBackwardPagination;

/**
 * Pagination information about the search results.
 */
export type SearchQueryPageResponse = {
    /**
     * Total items matching the criteria.
     */
    totalItems: number;
    /**
     * Indicates whether the `totalItems` value has been capped due to system limits. When true, `totalItems` is a lower bound and the actual number of matching items is greater than the reported value.
     *
     */
    hasMoreTotalItems: boolean;
    /**
     * The cursor value for getting the previous page of results. Use this in the `before` field of an ensuing request.
     */
    startCursor: StartCursor | null;
    /**
     * The cursor value for getting the next page of results. Use this in the `after` field of an ensuing request.
     */
    endCursor: EndCursor | null;
};

export type SearchQueryRequest = {
    /**
     * Pagination criteria.
     */
    page?: SearchQueryPageRequest;
};

export type SearchQueryResponse = {
    page: SearchQueryPageResponse;
};

/**
 * The order in which to sort the related field.
 */
export type SortOrderEnum = 'ASC' | 'DESC';

export type SearchAgentInstancesData = {
    body?: AgentInstanceSearchQuery;
    path?: never;
    query?: never;
    url: '/agent-instances/search';
};

export type SearchAgentInstancesErrors = {
    /**
     * The provided data is not valid.
     */
    400: ProblemDetail;
    /**
     * The request lacks valid authentication credentials.
     */
    401: ProblemDetail;
    /**
     * Forbidden. The request is not allowed.
     */
    403: ProblemDetail;
    /**
     * An internal error occurred while processing the request.
     */
    500: ProblemDetail;
};

export type SearchAgentInstancesError = SearchAgentInstancesErrors[keyof SearchAgentInstancesErrors];

export type SearchAgentInstancesResponses = {
    /**
     * The agent instance search result.
     */
    200: AgentInstanceSearchQueryResult;
};

export type SearchAgentInstancesResponse = SearchAgentInstancesResponses[keyof SearchAgentInstancesResponses];

export type SearchAgentInstanceHistoryData = {
    body?: AgentInstanceHistorySearchQuery;
    path: {
        /**
         * The key of the agent instance whose history to search.
         */
        agentInstanceKey: AgentInstanceKey;
    };
    query?: never;
    url: '/agent-instances/{agentInstanceKey}/history/search';
};

export type SearchAgentInstanceHistoryErrors = {
    /**
     * The provided data is not valid.
     */
    400: ProblemDetail;
    /**
     * The request lacks valid authentication credentials.
     */
    401: ProblemDetail;
    /**
     * Forbidden. The request is not allowed.
     */
    403: ProblemDetail;
    /**
     * The agent instance with the given key was not found.
     * More details are provided in the response body.
     *
     */
    404: ProblemDetail;
    /**
     * An internal error occurred while processing the request.
     */
    500: ProblemDetail;
};

export type SearchAgentInstanceHistoryError = SearchAgentInstanceHistoryErrors[keyof SearchAgentInstanceHistoryErrors];

export type SearchAgentInstanceHistoryResponses = {
    /**
     * The agent instance history search result.
     */
    200: AgentInstanceHistorySearchQueryResult;
};

export type SearchAgentInstanceHistoryResponse = SearchAgentInstanceHistoryResponses[keyof SearchAgentInstanceHistoryResponses];
