//! Spec-generated response-contract validation for the REST gateway
//! (Magikcraft/nano-bpm#1011).
//!
//! For every **implemented** operation this validates the outgoing response
//! (status code + serialized JSON body) against the OpenAPI response schema for
//! that exact status. On a violation it fails loudly with **500** and a
//! machine-readable body naming the offending JSON Pointer(s) and rule(s) —
//! turning silent contract drift (the motivating case: a JOB wait state missing
//! the required `details.jobType`, silently skipped by a Zeebe-correct client,
//! see #1010) into an immediate, attributable error at the source.
//!
//! Derivation over duplication: the per-`(operationId, status)` schemas are NOT
//! hand-written. They are generated from the same `spec/` tree that generates
//! the server, by `scripts/gen-response-contract.py`, into the git-ignored
//! `response_contract_schema.json` bundled here via `include_str!`. Because that
//! bundle is regenerated by `make generate` (which CI runs before every build,
//! exactly as it does for the git-ignored `generated/` crate and
//! `stub_impls.rs`), the validators can never be stale versus the spec.
//!
//! Scope guard: only operations wired to the engine (the `implemented` flag,
//! sourced from `gen-stub-server.py`'s OVERRIDES map) are validated. Every
//! unwired operation returns `Err(())` -> `501 Not Implemented` and is left
//! untouched, so a 501 stub is never reinterpreted as a 500.
//!
//! Enforced JSON-Schema facets: `type`, `required`, `enum`/`const`, `nullable`
//! (translated to an explicit null alternative at generation time), plus
//! `allOf`/`anyOf`/`oneOf`, `items`, `properties`, and `additionalProperties`.
//! `format` and numeric range facets are carried but treated as annotations
//! (not asserted) to avoid false-positive 500s on the hot path from
//! Camunda-specific/custom formats.

use std::collections::HashMap;
use std::sync::OnceLock;

use axum::body::Body;
use axum::extract::{MatchedPath, Request};
use axum::middleware::Next;
use axum::response::Response;
use http::StatusCode;
use http::header::{CONTENT_LENGTH, CONTENT_TYPE};
use serde::Serialize;
use serde_json::Value;

/// The generated contract bundle (git-ignored, produced by `make generate`).
const CONTRACT_JSON: &str = include_str!("response_contract_schema.json");

/// Runtime enforcement mode, from `NANOBPM_RESPONSE_VALIDATION`.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Mode {
    /// Validate and fail with 500 on any violation (default; always-on in
    /// dev/CI/`urban check`-style runs).
    Strict,
    /// Validate and log a warning, but pass the response through unchanged. The
    /// prod-safe toggle for aggressive adoption without a hot-path foot-gun.
    Lenient,
    /// Disabled: no buffering, no validation, zero overhead.
    Off,
}

fn parse_mode(raw: Option<&str>) -> Mode {
    match raw.map(|s| s.trim().to_ascii_lowercase()).as_deref() {
        Some("off") | Some("disabled") | Some("false") | Some("0") | Some("none") => Mode::Off,
        Some("lenient") | Some("warn") | Some("observe") => Mode::Lenient,
        // Unset, "strict", "on", "1", or anything else -> strict (fail loud).
        _ => Mode::Strict,
    }
}

fn mode() -> Mode {
    static MODE: OnceLock<Mode> = OnceLock::new();
    *MODE.get_or_init(|| parse_mode(std::env::var("NANOBPM_RESPONSE_VALIDATION").ok().as_deref()))
}

/// Default ceiling (bytes) on how much response body the guard will buffer for
/// validation when no smaller limit is configured. Validation is inherently
/// O(body size) in memory, so this caps a single response's footprint. 8 MiB
/// comfortably covers realistic JSON pages while preventing a very large
/// response (or a large `pageSize`) from forcing an unbounded buffer (OOM/DoS).
const DEFAULT_MAX_BUFFER_BYTES: usize = 8 * 1024 * 1024;

fn parse_max_bytes(raw: Option<&str>) -> usize {
    raw.map(str::trim)
        .and_then(|s| s.parse::<usize>().ok())
        .filter(|&n| n > 0)
        .unwrap_or(DEFAULT_MAX_BUFFER_BYTES)
}

/// Maximum response body size (bytes) the guard will buffer for validation,
/// from `NANOBPM_RESPONSE_VALIDATION_MAX_BYTES` (default 8 MiB). A response that
/// declares a larger body via `Content-Length` is passed through unvalidated
/// (never buffered). A response with a missing or dishonest length that streams
/// past this cap cannot be passed through (its body is already partly consumed),
/// so the guard fails loudly with a structured 500 instead. Either way,
/// validation can never buffer more than this and exhaust memory.
fn max_buffer_bytes() -> usize {
    static MAX: OnceLock<usize> = OnceLock::new();
    *MAX.get_or_init(|| {
        parse_max_bytes(
            std::env::var("NANOBPM_RESPONSE_VALIDATION_MAX_BYTES")
                .ok()
                .as_deref(),
        )
    })
}

/// A single contract violation, machine-readable in the 500 body.
#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub struct Violation {
    /// RFC 6901 JSON Pointer into the response body (`""` = the whole body).
    pub pointer: String,
    /// The failing schema rule, e.g. `required`, `type`, `enum`.
    pub rule: String,
    /// Human-readable detail, e.g. `required property missing: jobType`.
    pub detail: String,
}

impl Violation {
    fn new(pointer: &str, rule: &str, detail: impl Into<String>) -> Self {
        Violation {
            pointer: pointer.to_string(),
            rule: rule.to_string(),
            detail: detail.into(),
        }
    }
}

struct Operation {
    operation_id: String,
    implemented: bool,
    /// status code -> translated JSON-Schema for that response body.
    responses: HashMap<u16, Value>,
}

/// The parsed, indexed response contract.
struct Contract {
    /// Shared `$defs` pool referenced as `#/defs/<Name>`.
    defs: serde_json::Map<String, Value>,
    /// Every operation with at least one JSON response schema.
    ops: Vec<Operation>,
    /// `"<METHOD> <normalized-path>"` -> index into `ops` (outbound guard).
    by_route: HashMap<String, usize>,
    /// operationId -> index into `ops`. Direct-by-id lookup backs the pure
    /// `validate_operation`/`is_implemented` API (exercised by the crate's
    /// tests); the hot path uses `by_route`.
    #[allow(dead_code)]
    by_id: HashMap<String, usize>,
}

fn contract() -> &'static Contract {
    static STORE: OnceLock<Contract> = OnceLock::new();
    STORE.get_or_init(load_contract)
}

fn load_contract() -> Contract {
    let root: Value = serde_json::from_str(CONTRACT_JSON).expect(
        "response_contract_schema.json is not valid JSON (regenerate with `make generate`)",
    );

    let defs = root
        .get("defs")
        .and_then(Value::as_object)
        .cloned()
        .unwrap_or_default();

    let mut ops: Vec<Operation> = Vec::new();
    let mut by_route: HashMap<String, usize> = HashMap::new();
    let mut by_id: HashMap<String, usize> = HashMap::new();

    if let Some(list) = root.get("operations").and_then(Value::as_array) {
        for entry in list {
            let operation_id = entry
                .get("operationId")
                .and_then(Value::as_str)
                .unwrap_or_default()
                .to_string();
            let method = entry
                .get("method")
                .and_then(Value::as_str)
                .unwrap_or_default();
            let path = entry
                .get("path")
                .and_then(Value::as_str)
                .unwrap_or_default();
            let implemented = entry
                .get("implemented")
                .and_then(Value::as_bool)
                .unwrap_or(false);

            let mut responses: HashMap<u16, Value> = HashMap::new();
            if let Some(resp_map) = entry.get("responses").and_then(Value::as_object) {
                for (status, schema) in resp_map {
                    if let Ok(code) = status.parse::<u16>() {
                        responses.insert(code, schema.clone());
                    }
                }
            }

            let route_key = format!("{method} {}", normalize_path(path));
            let idx = ops.len();
            by_id.insert(operation_id.clone(), idx);
            by_route.insert(route_key, idx);
            ops.push(Operation {
                operation_id,
                implemented,
                responses,
            });
        }
    }

    Contract {
        defs,
        ops,
        by_route,
        by_id,
    }
}

/// `/v2/foo/{barKey}` -> `/v2/foo/{}` so route lookup is independent of the
/// (differently-cased) path-parameter names the axum router uses.
fn normalize_path(path: &str) -> String {
    let mut out = String::with_capacity(path.len());
    let mut in_param = false;
    for ch in path.chars() {
        match ch {
            '{' => {
                in_param = true;
                out.push('{');
            }
            '}' => {
                in_param = false;
                out.push('}');
            }
            _ if in_param => {}
            _ => out.push(ch),
        }
    }
    out
}

// ---------------------------------------------------------------------------
// Validation core
// ---------------------------------------------------------------------------

const MAX_DEPTH: usize = 256;

fn json_type_matches(ty: &str, instance: &Value) -> bool {
    match ty {
        "null" => instance.is_null(),
        "boolean" => instance.is_boolean(),
        "string" => instance.is_string(),
        "number" => instance.is_number(),
        "integer" => {
            instance.is_i64()
                || instance.is_u64()
                || instance
                    .as_f64()
                    .is_some_and(|f| f.fract() == 0.0 && f.is_finite())
        }
        "object" => instance.is_object(),
        "array" => instance.is_array(),
        _ => true, // unknown type keyword: don't assert
    }
}

fn type_name(instance: &Value) -> &'static str {
    match instance {
        Value::Null => "null",
        Value::Bool(_) => "boolean",
        Value::Number(_) => "number",
        Value::String(_) => "string",
        Value::Array(_) => "array",
        Value::Object(_) => "object",
    }
}

fn child_pointer(pointer: &str, token: &str) -> String {
    // RFC 6901 escaping.
    let escaped = token.replace('~', "~0").replace('/', "~1");
    format!("{pointer}/{escaped}")
}

/// Validate `instance` against `schema`, appending any violations to `out`.
fn validate(
    defs: &serde_json::Map<String, Value>,
    schema: &Value,
    instance: &Value,
    pointer: &str,
    out: &mut Vec<Violation>,
    depth: usize,
) {
    if depth > MAX_DEPTH {
        // The recursion guard is a drift-detection surface: silently returning
        // here would accept the value, turning a pathologically deep response
        // (or a cyclic `$ref` alias) into a false negative. Surface it as a
        // structured violation so the guard fails loudly instead of quietly
        // treating an unvalidated value as conformant.
        out.push(Violation::new(
            pointer,
            "depth",
            format!("validation depth exceeded {MAX_DEPTH} levels"),
        ));
        return;
    }
    let Some(obj) = schema.as_object() else {
        // `true`/`{}` accept anything; `false` rejects everything.
        if schema.as_bool() == Some(false) {
            out.push(Violation::new(
                pointer,
                "schema",
                "schema `false` rejects all values",
            ));
        }
        return;
    };

    // $ref -> resolve within the shared defs pool.
    if let Some(reference) = obj.get("$ref").and_then(Value::as_str) {
        if let Some(name) = reference.strip_prefix("#/defs/")
            && let Some(target) = defs.get(name)
        {
            validate(defs, target, instance, pointer, out, depth + 1);
        }
        return;
    }

    // type
    if let Some(ty) = obj.get("type") {
        let ok = match ty {
            Value::String(s) => json_type_matches(s, instance),
            Value::Array(list) => list
                .iter()
                .filter_map(Value::as_str)
                .any(|s| json_type_matches(s, instance)),
            _ => true,
        };
        if !ok {
            let expected = match ty {
                Value::String(s) => s.clone(),
                other => other.to_string(),
            };
            out.push(Violation::new(
                pointer,
                "type",
                format!("expected type {expected}, got {}", type_name(instance)),
            ));
            // A wrong-typed value can't meaningfully satisfy the object/array
            // sub-checks below; stop here to avoid cascading noise.
            return;
        }
    }

    // enum
    if let Some(Value::Array(values)) = obj.get("enum")
        && !values.iter().any(|v| v == instance)
    {
        out.push(Violation::new(
            pointer,
            "enum",
            format!(
                "value {} is not one of the permitted enum values",
                compact(instance)
            ),
        ));
    }

    // const
    if let Some(expected) = obj.get("const")
        && expected != instance
    {
        out.push(Violation::new(
            pointer,
            "const",
            format!(
                "value {} does not equal the required const",
                compact(instance)
            ),
        ));
    }

    // allOf: every subschema must hold.
    if let Some(Value::Array(subs)) = obj.get("allOf") {
        for sub in subs {
            validate(defs, sub, instance, pointer, out, depth + 1);
        }
    }

    // anyOf / oneOf: at least one subschema must hold. (oneOf is validated with
    // anyOf semantics — >= 1 — because the spec's discriminated unions overlap
    // structurally and strict exactly-one would false-positive.)
    //
    // On failure we surface the violations of the *most likely intended* branch
    // (fewest violations) rather than an opaque "matches nothing" — critically,
    // for the pervasive `nullable` idiom (`anyOf: [ {type: null}, <schema> ]`) on
    // a non-null value we skip the null branch so the precise inner pointer/rule
    // (e.g. `…/jobType: required property missing`) reaches the caller.
    for key in ["anyOf", "oneOf"] {
        if let Some(Value::Array(subs)) = obj.get(key) {
            let mut matched = false;
            let mut best: Option<Vec<Violation>> = None;
            for sub in subs {
                let branch = branch_violations(defs, sub, instance, pointer, depth + 1);
                if branch.is_empty() {
                    matched = true;
                    break;
                }
                // Prefer a structural branch over the null alternative when the
                // value isn't null.
                if is_null_type_schema(sub) && !instance.is_null() {
                    continue;
                }
                if best.as_ref().is_none_or(|b| branch.len() < b.len()) {
                    best = Some(branch);
                }
            }
            if !matched {
                match best {
                    Some(mut branch) => out.append(&mut branch),
                    None => out.push(Violation::new(
                        pointer,
                        key,
                        format!("value does not match any of the {key} permitted schemas"),
                    )),
                }
            }
        }
    }

    // Object facets.
    if let Some(map) = instance.as_object() {
        if let Some(Value::Array(required)) = obj.get("required") {
            for req in required.iter().filter_map(Value::as_str) {
                if !map.contains_key(req) {
                    out.push(Violation::new(
                        &child_pointer(pointer, req),
                        "required",
                        format!("required property missing: {req}"),
                    ));
                }
            }
        }

        let properties = obj.get("properties").and_then(Value::as_object);
        if let Some(props) = properties {
            for (name, sub) in props {
                if let Some(child) = map.get(name) {
                    validate(
                        defs,
                        sub,
                        child,
                        &child_pointer(pointer, name),
                        out,
                        depth + 1,
                    );
                }
            }
        }

        match obj.get("additionalProperties") {
            Some(Value::Bool(false)) => {
                for name in map.keys() {
                    let known = properties.is_some_and(|p| p.contains_key(name));
                    if !known {
                        out.push(Violation::new(
                            &child_pointer(pointer, name),
                            "additionalProperties",
                            format!("unexpected property not permitted by the schema: {name}"),
                        ));
                    }
                }
            }
            Some(ap @ Value::Object(_)) => {
                for (name, child) in map {
                    let known = properties.is_some_and(|p| p.contains_key(name));
                    if !known {
                        validate(
                            defs,
                            ap,
                            child,
                            &child_pointer(pointer, name),
                            out,
                            depth + 1,
                        );
                    }
                }
            }
            _ => {}
        }
    }

    // Array items.
    if let (Some(items_schema), Some(arr)) = (obj.get("items"), instance.as_array()) {
        for (idx, elem) in arr.iter().enumerate() {
            validate(
                defs,
                items_schema,
                elem,
                &child_pointer(pointer, &idx.to_string()),
                out,
                depth + 1,
            );
        }
    }
}

/// Validate one `anyOf`/`oneOf` branch, returning its violations (at the real
/// `pointer`) without mutating the parent's list.
fn branch_violations(
    defs: &serde_json::Map<String, Value>,
    schema: &Value,
    instance: &Value,
    pointer: &str,
    depth: usize,
) -> Vec<Violation> {
    let mut scratch = Vec::new();
    validate(defs, schema, instance, pointer, &mut scratch, depth);
    scratch
}

/// True for the `{ "type": "null" }` sentinel the generator emits for the
/// `nullable` alternative.
fn is_null_type_schema(schema: &Value) -> bool {
    schema
        .as_object()
        .and_then(|o| o.get("type"))
        .and_then(Value::as_str)
        == Some("null")
}

fn compact(value: &Value) -> String {
    let s = value.to_string();
    // Truncate on a char boundary: `&s[..80]` would panic if byte 80 landed in
    // the middle of a multi-byte UTF-8 codepoint (turning a contract violation
    // into a 500 + panic instead of a structured error).
    match s.char_indices().nth(80) {
        Some((idx, _)) => format!("{}…", &s[..idx]),
        None => s,
    }
}

// ---------------------------------------------------------------------------
// Public validation entry points
// ---------------------------------------------------------------------------

/// Validate a response `body` for an operation identified by `operation_id` at
/// `status`. Returns the list of violations (empty = conformant). The pure
/// core of the contract check, used directly by the crate's tests; the outbound
/// `guard` reaches the same logic via `validate_against_op` on a route match. If
/// the operation or status has no schema, returns no violations.
#[allow(dead_code)]
pub fn validate_operation(operation_id: &str, status: u16, body: &Value) -> Vec<Violation> {
    let store = contract();
    let Some(&idx) = store.by_id.get(operation_id) else {
        return Vec::new();
    };
    validate_against_op(&store.defs, &store.ops[idx], status, body)
}

fn validate_against_op(
    defs: &serde_json::Map<String, Value>,
    op: &Operation,
    status: u16,
    body: &Value,
) -> Vec<Violation> {
    let Some(schema) = op.responses.get(&status) else {
        return Vec::new();
    };
    let mut out = Vec::new();
    validate(defs, schema, body, "", &mut out, 0);
    out
}

/// True when `operation_id` is wired to the engine (i.e. its success path is
/// subject to validation). Part of the pure API exercised by tests.
#[allow(dead_code)]
pub fn is_implemented(operation_id: &str) -> bool {
    let store = contract();
    store
        .by_id
        .get(operation_id)
        .map(|&idx| store.ops[idx].implemented)
        .unwrap_or(false)
}

// ---------------------------------------------------------------------------
// Outbound middleware
// ---------------------------------------------------------------------------

fn is_json_content_type(resp: &Response) -> bool {
    resp.headers()
        .get(CONTENT_TYPE)
        .and_then(|v| v.to_str().ok())
        .map(|ct| {
            let ct = ct.to_ascii_lowercase();
            ct.starts_with("application/json") || ct.starts_with("application/problem+json")
        })
        .unwrap_or(false)
}

/// The response's declared body size, if it carries a parseable `Content-Length`.
fn content_length(resp: &Response) -> Option<usize> {
    resp.headers()
        .get(CONTENT_LENGTH)
        .and_then(|v| v.to_str().ok())
        .and_then(|s| s.trim().parse::<usize>().ok())
}

/// Outbound response-contract guard. Applied to the generated `/v2` router so it
/// sees the serialized body just before it goes on the wire, keyed by the
/// matched route + status. Only implemented operations with a JSON body for the
/// returned status are validated; everything else (unimplemented 501 stubs,
/// non-JSON/binary/streaming bodies, unmatched routes) passes through untouched
/// and un-buffered.
pub async fn guard(req: Request, next: Next) -> Response {
    guard_with_mode(req, next, mode()).await
}

async fn guard_with_mode(req: Request, next: Next, current_mode: Mode) -> Response {
    guard_impl(req, next, current_mode, max_buffer_bytes()).await
}

async fn guard_impl(req: Request, next: Next, current_mode: Mode, max_bytes: usize) -> Response {
    if current_mode == Mode::Off {
        return next.run(req).await;
    }

    let method = req.method().as_str().to_string();
    let matched = req
        .extensions()
        .get::<MatchedPath>()
        .map(|m| m.as_str().to_string());

    let resp = next.run(req).await;

    // Resolve the operation for this route; bail out (untouched) if unknown or
    // not an implemented op.
    let Some(matched) = matched else {
        return resp;
    };
    let route_key = format!("{method} {}", normalize_path(&matched));
    let store = contract();
    let Some(&op_idx) = store.by_route.get(&route_key) else {
        return resp;
    };
    let op = &store.ops[op_idx];
    if !op.implemented {
        return resp;
    }

    let status = resp.status().as_u16();
    if !op.responses.contains_key(&status) {
        return resp;
    }
    if !is_json_content_type(&resp) {
        return resp;
    }

    // Bound the memory validation is willing to buffer. If the response already
    // declares a body larger than the limit, skip validation and pass it through
    // untouched rather than buffering it — this avoids consuming the body and
    // prevents an OOM/DoS from a very large page.
    if let Some(len) = content_length(&resp)
        && len > max_bytes
    {
        tracing::warn!(
            target: "response_contract",
            operation = %op.operation_id,
            status,
            content_length = len,
            max_bytes,
            "response body exceeds contract-validation buffer limit; passing through unvalidated"
        );
        return resp;
    }

    // Buffer the (JSON) body so we can validate it, then either pass it through
    // or replace it with a 500. `to_bytes` is capped at `max_bytes` so a missing
    // or dishonest Content-Length still can't force an unbounded buffer; if the
    // body streams past the cap `to_bytes` errors and we fail loudly below.
    let (parts, body) = resp.into_parts();
    let bytes = match axum::body::to_bytes(body, max_bytes).await {
        Ok(b) => b,
        Err(err) => {
            // The body stream is now partially consumed and unrecoverable, so we
            // cannot pass the original response through. Returning `parts` with an
            // empty body would ship a corrupt response (e.g. a stale
            // Content-Length that no longer matches the empty body) and bury the
            // I/O error. Fail loudly with a structured 500 instead.
            tracing::error!(
                target: "response_contract",
                operation = %op.operation_id,
                status,
                "failed to buffer response body for contract validation: {err}"
            );
            return buffer_failure_response(&op.operation_id, status);
        }
    };

    let violations = match serde_json::from_slice::<Value>(&bytes) {
        Ok(value) => validate_against_op(&store.defs, op, status, &value),
        Err(err) => vec![Violation::new(
            "",
            "type",
            format!("response body is not valid JSON: {err}"),
        )],
    };

    if violations.is_empty() {
        return Response::from_parts(parts, Body::from(bytes));
    }

    match current_mode {
        Mode::Lenient => {
            tracing::warn!(
                target: "response_contract",
                operation = %op.operation_id,
                status,
                violations = violations.len(),
                "response contract violation (lenient: passing through): {:?}",
                violations
            );
            Response::from_parts(parts, Body::from(bytes))
        }
        // Strict (Off handled above).
        _ => {
            tracing::error!(
                target: "response_contract",
                operation = %op.operation_id,
                status,
                violations = violations.len(),
                "response contract violation -> 500: {:?}",
                violations
            );
            violation_response(&op.operation_id, status, &violations)
        }
    }
}

fn violation_response(operation_id: &str, status: u16, violations: &[Violation]) -> Response {
    let body = serde_json::json!({
        "error": "response_contract_violation",
        "message": "The gateway produced a response that violates its own OpenAPI contract; \
                    failing loudly to surface contract drift (see Magikcraft/nano-bpm#1011).",
        "operationId": operation_id,
        "status": status,
        "violations": violations,
    });
    Response::builder()
        .status(StatusCode::INTERNAL_SERVER_ERROR)
        .header(CONTENT_TYPE, "application/json")
        .body(Body::from(body.to_string()))
        .unwrap_or_else(|_| {
            let mut fallback = Response::new(Body::from("response_contract_violation"));
            *fallback.status_mut() = StatusCode::INTERNAL_SERVER_ERROR;
            fallback
        })
}

/// Structured 500 for when the response body could not be buffered for
/// validation. The body stream is unrecoverable at that point, so we cannot pass
/// the original response through without risking a corrupt (mismatched
/// Content-Length) reply; fail loudly instead.
fn buffer_failure_response(operation_id: &str, status: u16) -> Response {
    let body = serde_json::json!({
        "error": "response_contract_buffer_failed",
        "message": "The gateway could not buffer its own response body to validate it \
                    against its OpenAPI contract; failing loudly rather than shipping a \
                    possibly-corrupt response (see Magikcraft/nano-bpm#1011).",
        "operationId": operation_id,
        "status": status,
    });
    Response::builder()
        .status(StatusCode::INTERNAL_SERVER_ERROR)
        .header(CONTENT_TYPE, "application/json")
        .body(Body::from(body.to_string()))
        .unwrap_or_else(|_| {
            let mut fallback = Response::new(Body::from("response_contract_buffer_failed"));
            *fallback.status_mut() = StatusCode::INTERNAL_SERVER_ERROR;
            fallback
        })
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;

    fn defs() -> serde_json::Map<String, Value> {
        contract().defs.clone()
    }

    fn v(schema: &Value, instance: &Value) -> Vec<Violation> {
        let mut out = Vec::new();
        validate(&defs(), schema, instance, "", &mut out, 0);
        out
    }

    #[test]
    fn depth_cap_surfaces_a_violation_instead_of_silently_accepting() {
        // The recursion guard must fail loudly on drift, not silently accept a
        // value once MAX_DEPTH is exceeded (a false negative). Build a schema +
        // instance nested past the cap and assert a structured `depth` violation
        // surfaces rather than an empty (conformant) result.
        let mut schema = json!({"type": "object"});
        let mut instance = json!({});
        for _ in 0..(MAX_DEPTH + 2) {
            schema = json!({"type": "object", "properties": {"a": schema}});
            instance = json!({"a": instance});
        }
        let out = v(&schema, &instance);
        assert!(
            out.iter().any(|viol| viol.rule == "depth"),
            "expected a depth-cap violation, got {out:?}"
        );
    }

    #[test]
    fn parse_mode_variants() {
        assert_eq!(parse_mode(None), Mode::Strict);
        assert_eq!(parse_mode(Some("strict")), Mode::Strict);
        assert_eq!(parse_mode(Some("STRICT")), Mode::Strict);
        assert_eq!(parse_mode(Some("lenient")), Mode::Lenient);
        assert_eq!(parse_mode(Some("warn")), Mode::Lenient);
        assert_eq!(parse_mode(Some("off")), Mode::Off);
        assert_eq!(parse_mode(Some("0")), Mode::Off);
    }

    #[test]
    fn parse_max_bytes_variants() {
        // Unset / unparseable / non-positive all fall back to the default.
        assert_eq!(parse_max_bytes(None), DEFAULT_MAX_BUFFER_BYTES);
        assert_eq!(parse_max_bytes(Some("")), DEFAULT_MAX_BUFFER_BYTES);
        assert_eq!(parse_max_bytes(Some("nope")), DEFAULT_MAX_BUFFER_BYTES);
        assert_eq!(parse_max_bytes(Some("0")), DEFAULT_MAX_BUFFER_BYTES);
        assert_eq!(parse_max_bytes(Some("-5")), DEFAULT_MAX_BUFFER_BYTES);
        // A positive value (with surrounding whitespace) is honoured.
        assert_eq!(parse_max_bytes(Some(" 4096 ")), 4096);
    }

    #[test]
    fn normalize_path_strips_param_names() {
        assert_eq!(normalize_path("/v2/foo/{barKey}"), "/v2/foo/{}");
        assert_eq!(normalize_path("/v2/a/{x}/b/{y}"), "/v2/a/{}/b/{}");
        assert_eq!(normalize_path("/v2/plain"), "/v2/plain");
    }

    #[test]
    fn compact_truncates_non_ascii_without_panicking() {
        // Byte 80 lands mid-codepoint for a multi-byte string; `&s[..80]` would
        // panic. compact() must truncate on a char boundary instead, so a
        // contract violation on a non-ASCII value surfaces as a structured error
        // rather than a 500 + panic.
        let long_unicode = "é".repeat(200);
        let out = compact(&Value::String(long_unicode));
        assert!(out.ends_with('…'));
        assert!(out.is_char_boundary(out.len()));

        // Short values pass through untouched (no ellipsis).
        let short = compact(&Value::String("héllo".to_string()));
        assert_eq!(short, "\"héllo\"");
    }

    #[test]
    fn contract_loads_and_indexes() {
        // The bundle parses and the motivating operation is present + implemented.
        assert!(is_implemented("searchElementInstanceWaitStates"));
        // An unimplemented operation is known but not validated.
        assert!(!is_implemented("createUser"));
    }

    #[test]
    fn required_type_and_enum() {
        let schema = json!({
            "type": "object",
            "required": ["a", "b"],
            "properties": {
                "a": {"type": "string"},
                "b": {"enum": ["X", "Y"]}
            }
        });
        assert!(v(&schema, &json!({"a": "hi", "b": "X"})).is_empty());

        let missing = v(&schema, &json!({"a": "hi"}));
        assert_eq!(missing.len(), 1);
        assert_eq!(missing[0].rule, "required");
        assert_eq!(missing[0].pointer, "/b");

        let bad_type = v(&schema, &json!({"a": 3, "b": "X"}));
        assert_eq!(bad_type[0].rule, "type");
        assert_eq!(bad_type[0].pointer, "/a");

        let bad_enum = v(&schema, &json!({"a": "hi", "b": "Z"}));
        assert_eq!(bad_enum[0].rule, "enum");
        assert_eq!(bad_enum[0].pointer, "/b");
    }

    #[test]
    fn nullable_is_translated_to_null_alternative() {
        // Mirrors the generator's output for `nullable: true` + a typed value.
        let schema = json!({"anyOf": [{"type": "null"}, {"type": "integer"}]});
        assert!(v(&schema, &json!(null)).is_empty());
        assert!(v(&schema, &json!(7)).is_empty());
        assert_eq!(v(&schema, &json!("x")).len(), 1);
    }

    #[test]
    fn nested_pointer_reported() {
        let schema = json!({
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": ["jobType"],
                        "properties": {"jobType": {"type": "string"}}
                    }
                }
            }
        });
        let bad = v(&schema, &json!({"items": [{"jobKey": "1"}]}));
        assert_eq!(bad.len(), 1);
        assert_eq!(bad[0].pointer, "/items/0/jobType");
        assert!(bad[0].detail.contains("jobType"));
    }

    /// The motivating case: a JOB wait state whose `jobType` is absent must be
    /// caught against the real spec-generated schema.
    #[test]
    fn wait_state_missing_job_type_is_a_violation() {
        let conformant = json!({
            "page": {"totalItems": 1, "hasMoreTotalItems": false,
                     "startCursor": null, "endCursor": null},
            "items": [{
                "processInstanceKey": "1",
                "elementInstanceKey": "2",
                "elementId": "task",
                "elementType": "SERVICE_TASK",
                "tenantId": "<default>",
                "rootProcessInstanceKey": "1",
                "bpmnProcessId": "proc",
                "details": {
                    "waitStateType": "JOB",
                    "jobKey": "9",
                    "jobType": "worker-a",
                    "jobKind": "BPMN_ELEMENT",
                    "listenerEventType": null,
                    "retries": 3
                }
            }]
        });
        assert!(
            validate_operation("searchElementInstanceWaitStates", 200, &conformant).is_empty(),
            "a conformant wait-state result must pass untouched"
        );

        // Force-blank jobType -> the exact drift from #1010.
        let mut drifted = conformant.clone();
        drifted["items"][0]["details"]
            .as_object_mut()
            .unwrap()
            .remove("jobType");
        let violations = validate_operation("searchElementInstanceWaitStates", 200, &drifted);
        assert!(
            violations.iter().any(|x| x.rule == "required"
                && x.detail.contains("jobType")
                && x.pointer.ends_with("/jobType")),
            "missing jobType must be reported, got {violations:?}"
        );
    }

    #[test]
    fn unknown_operation_or_status_is_noop() {
        assert!(validate_operation("thisIsNotAnOperation", 200, &json!({})).is_empty());
        // A status with no documented schema is not asserted.
        assert!(validate_operation("searchElementInstanceWaitStates", 418, &json!({})).is_empty());
    }

    /// Golden: a conformant (empty) search result passes untouched across the
    /// implemented read endpoints (element-instances, jobs, user-tasks,
    /// incidents, process-instances). An empty `items` list with a valid `page`
    /// satisfies every `*SearchQueryResult` 200 schema.
    #[test]
    fn conformant_empty_search_results_pass() {
        let empty = json!({
            "items": [],
            "page": {
                "totalItems": 0,
                "hasMoreTotalItems": false,
                "startCursor": null,
                "endCursor": null
            }
        });
        for op in [
            "searchElementInstances",
            "searchJobs",
            "searchUserTasks",
            "searchIncidents",
            "searchProcessInstances",
        ] {
            assert!(is_implemented(op), "{op} should be implemented");
            let violations = validate_operation(op, 200, &empty);
            assert!(
                violations.is_empty(),
                "conformant empty result for {op} must pass, got {violations:?}"
            );
        }
    }
}

/// End-to-end tests over the outbound guard: a crafted response flows through a
/// real axum Router + the `guard` layer, exercising route matching (MatchedPath),
/// status/schema lookup, and the strict 500-on-violation rewrite.
#[cfg(test)]
mod middleware_tests {
    use axum::Router;
    use axum::routing::post;
    use serde_json::json;
    use tower::ServiceExt;

    use super::*;

    const WAIT_STATES_ROUTE: &str = "/v2/element-instances/wait-states/search";

    fn conformant_wait_state_body() -> Value {
        json!({
            "page": {"totalItems": 1, "hasMoreTotalItems": false,
                     "startCursor": null, "endCursor": null},
            "items": [{
                "processInstanceKey": "1",
                "elementInstanceKey": "2",
                "elementId": "task",
                "elementType": "SERVICE_TASK",
                "tenantId": "<default>",
                "rootProcessInstanceKey": "1",
                "bpmnProcessId": "proc",
                "details": {
                    "waitStateType": "JOB",
                    "jobKey": "9",
                    "jobType": "worker-a",
                    "jobKind": "BPMN_ELEMENT",
                    "listenerEventType": null,
                    "retries": 3
                }
            }]
        })
    }

    fn json_response(status: u16, body: Value) -> Response {
        Response::builder()
            .status(status)
            .header(CONTENT_TYPE, "application/json")
            .body(Body::from(body.to_string()))
            .unwrap()
    }

    fn app_with_guard(route: &str, mode: Mode, handler_status: u16, body: Value) -> Router {
        Router::new()
            .route(
                route,
                post(move || {
                    let body = body.clone();
                    async move { json_response(handler_status, body) }
                }),
            )
            .layer(axum::middleware::from_fn(move |req, next| {
                guard_with_mode(req, next, mode)
            }))
    }

    async fn run(app: Router) -> (u16, Value) {
        let req = Request::builder()
            .method("POST")
            .uri(WAIT_STATES_ROUTE)
            .body(Body::empty())
            .unwrap();
        let resp = app.oneshot(req).await.unwrap();
        let status = resp.status().as_u16();
        let bytes = axum::body::to_bytes(resp.into_body(), usize::MAX)
            .await
            .unwrap();
        let value = serde_json::from_slice(&bytes).unwrap_or(Value::Null);
        (status, value)
    }

    /// Acceptance: a response missing a `required` field returns 500 with a body
    /// naming the violation (the #1010 repro: a JOB wait state with no jobType).
    #[tokio::test]
    async fn missing_required_field_returns_500() {
        let mut body = conformant_wait_state_body();
        body["items"][0]["details"]
            .as_object_mut()
            .unwrap()
            .remove("jobType");

        let app = app_with_guard(WAIT_STATES_ROUTE, Mode::Strict, 200, body);
        let (status, value) = run(app).await;

        assert_eq!(status, 500, "a required-field violation must become a 500");
        assert_eq!(value["error"], "response_contract_violation");
        assert_eq!(value["operationId"], "searchElementInstanceWaitStates");
        assert_eq!(value["status"], 200);
        let violations = value["violations"].as_array().unwrap();
        assert!(
            violations
                .iter()
                .any(|v| v["rule"] == "required"
                    && v["detail"].as_str().unwrap().contains("jobType")),
            "500 body must name the jobType violation, got {value}"
        );
    }

    /// Acceptance: a conformant response passes through untouched (same status,
    /// same body).
    #[tokio::test]
    async fn conformant_response_passes_untouched() {
        let body = conformant_wait_state_body();
        let app = app_with_guard(WAIT_STATES_ROUTE, Mode::Strict, 200, body.clone());
        let (status, value) = run(app).await;
        assert_eq!(status, 200);
        assert_eq!(value, body);
    }

    /// In lenient mode a violation is logged but the (non-conformant) response is
    /// still returned unchanged — the prod-safe toggle.
    #[tokio::test]
    async fn lenient_mode_passes_violation_through() {
        let mut body = conformant_wait_state_body();
        body["items"][0]["details"]
            .as_object_mut()
            .unwrap()
            .remove("jobType");
        let app = app_with_guard(WAIT_STATES_ROUTE, Mode::Lenient, 200, body.clone());
        let (status, value) = run(app).await;
        assert_eq!(status, 200, "lenient mode must not rewrite to 500");
        assert_eq!(value, body);
    }

    /// Acceptance: an unimplemented operation still returns 501 — the guard never
    /// reinterprets a stub's 501 as a 500. `createUser` is a 501 stub (not in
    /// OVERRIDES), so its route is not validated.
    #[tokio::test]
    async fn unimplemented_operation_still_returns_501() {
        assert!(
            !is_implemented("createUser"),
            "test precondition: createUser is an unwired stub"
        );
        // The generated stub returns 501 with no JSON body; the guard must pass
        // it straight through.
        let route = "/v2/users";
        let app = Router::new()
            .route(
                route,
                post(|| async { Response::builder().status(501).body(Body::empty()).unwrap() }),
            )
            .layer(axum::middleware::from_fn(move |req, next| {
                guard_with_mode(req, next, Mode::Strict)
            }));
        let req = Request::builder()
            .method("POST")
            .uri(route)
            .body(Body::empty())
            .unwrap();
        let resp = app.oneshot(req).await.unwrap();
        assert_eq!(resp.status().as_u16(), 501);
    }

    /// A non-JSON body (e.g. XML) on an implemented op is never buffered or
    /// validated — it passes through untouched even in strict mode.
    #[tokio::test]
    async fn non_json_body_passes_through() {
        // get_process_definition_xml is implemented and returns XML.
        let route = "/v2/process-definitions/{processDefinitionKey}/xml";
        let app = Router::new()
            .route(
                route,
                axum::routing::get(|| async {
                    Response::builder()
                        .status(200)
                        .header(CONTENT_TYPE, "text/xml")
                        .body(Body::from("<definitions/>"))
                        .unwrap()
                }),
            )
            .layer(axum::middleware::from_fn(move |req, next| {
                guard_with_mode(req, next, Mode::Strict)
            }));
        let req = Request::builder()
            .method("GET")
            .uri("/v2/process-definitions/42/xml")
            .body(Body::empty())
            .unwrap();
        let resp = app.oneshot(req).await.unwrap();
        assert_eq!(resp.status().as_u16(), 200);
        let bytes = axum::body::to_bytes(resp.into_body(), usize::MAX)
            .await
            .unwrap();
        assert_eq!(&bytes[..], b"<definitions/>");
    }

    /// A response whose declared `Content-Length` exceeds the buffer limit is
    /// passed through unvalidated — the guard must not buffer it (OOM/DoS guard).
    /// Proven by using a body that *would* violate the contract: with the
    /// oversized Content-Length the guard skips validation and returns it as-is
    /// (200) instead of rewriting to 500.
    #[tokio::test]
    async fn oversized_content_length_passes_through_unvalidated() {
        let mut body = conformant_wait_state_body();
        body["items"][0]["details"]
            .as_object_mut()
            .unwrap()
            .remove("jobType");
        let serialized = body.to_string();
        let app = Router::new()
            .route(
                WAIT_STATES_ROUTE,
                post(move || {
                    let serialized = serialized.clone();
                    async move {
                        Response::builder()
                            .status(200)
                            .header(CONTENT_TYPE, "application/json")
                            // Declare a body far larger than the tiny limit below.
                            .header(CONTENT_LENGTH, "10000000")
                            .body(Body::from(serialized))
                            .unwrap()
                    }
                }),
            )
            .layer(axum::middleware::from_fn(move |req, next| {
                guard_impl(req, next, Mode::Strict, 16)
            }));
        let req = Request::builder()
            .method("POST")
            .uri(WAIT_STATES_ROUTE)
            .body(Body::empty())
            .unwrap();
        let resp = app.oneshot(req).await.unwrap();
        assert_eq!(
            resp.status().as_u16(),
            200,
            "oversized response must pass through unvalidated, not be rewritten to 500"
        );
    }

    /// A response with no honest length that streams past the buffer cap can't be
    /// buffered, so the guard fails loudly with a structured 500 rather than
    /// buffering unbounded memory. This is the bound that prevents OOM when
    /// Content-Length is absent or dishonest.
    #[tokio::test]
    async fn body_exceeding_cap_without_length_fails_loudly() {
        // A conformant body, but the cap is set below its size so it can't be
        // buffered. No Content-Length header is set, so the pre-check can't
        // short-circuit — the cap on `to_bytes` is what bounds memory.
        let body = conformant_wait_state_body();
        let serialized = body.to_string();
        assert!(
            serialized.len() > 16,
            "test needs a body larger than the cap"
        );
        let app = Router::new()
            .route(
                WAIT_STATES_ROUTE,
                post(move || {
                    let serialized = serialized.clone();
                    async move {
                        Response::builder()
                            .status(200)
                            .header(CONTENT_TYPE, "application/json")
                            .body(Body::from(serialized))
                            .unwrap()
                    }
                }),
            )
            .layer(axum::middleware::from_fn(move |req, next| {
                guard_impl(req, next, Mode::Strict, 16)
            }));
        let req = Request::builder()
            .method("POST")
            .uri(WAIT_STATES_ROUTE)
            .body(Body::empty())
            .unwrap();
        let resp = app.oneshot(req).await.unwrap();
        assert_eq!(resp.status().as_u16(), 500);
        let bytes = axum::body::to_bytes(resp.into_body(), usize::MAX)
            .await
            .unwrap();
        let value: Value = serde_json::from_slice(&bytes).unwrap_or(Value::Null);
        assert_eq!(value["error"], "response_contract_buffer_failed");
    }
}
